### ISSUE TITLE
设备api19 分享到小米盒子3 投屏失败， log如下，请问怎么解决

### ISSUE THREAD

**Issue by ximencx** [geniusgithub/MediaPlayer#4]
如下log
```
03-26 01:56:06.317 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out: CyberGarage warning : java.io.FileNotFoundException: /dev/666ddb97-36e1-6b13-ffff-ffffc7831a22/svc/upnp-org/AVTransport/desc.xml: open failed: ENOENT (No such file or directory)
03-26 01:56:06.317 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out: org.cybergarage.xml.ParserException: java.io.FileNotFoundException: /dev/666ddb97-36e1-6b13-ffff-ffffc7831a22/svc/upnp-org/AVTransport/desc.xml: open failed: ENOENT (No such file or directory)
03-26 01:56:06.317 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at org.cybergarage.xml.Parser.parse(Parser.java:107)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at org.cybergarage.upnp.Service.getSCPDNode(Service.java:422)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at org.cybergarage.upnp.Service.getSCPDNode(Service.java:471)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at org.cybergarage.upnp.Service.getActionList(Service.java:501)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at org.cybergarage.upnp.Service.getAction(Service.java:520)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at com.android.tedcoder.wkvideoplayer.dlna.engine.MultiPointController.play(MultiPointController.java:41)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at com.android.tedcoder.wkvideoplayer.view.SuperVideoPlayer$10.run(SuperVideoPlayer.java:648)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out: Caused by: java.io.FileNotFoundException: /dev/666ddb97-36e1-6b13-ffff-ffffc7831a22/svc/upnp-org/AVTransport/desc.xml: open failed: ENOENT (No such file or directory)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at libcore.io.IoBridge.open(IoBridge.java:409)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at java.io.FileInputStream.<init>(FileInputStream.java:78)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at org.cybergarage.xml.Parser.parse(Parser.java:101)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out: 	... 6 more
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out: Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at libcore.io.Posix.open(Native Method)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out:     at libcore.io.IoBridge.open(IoBridge.java:393)
03-26 01:56:06.327 5071-5171/com.android.tedcoder.androidvideoplayer I/System.out: 	... 8 more
```

**Comment by liulei9385** [comment]
同问，有解决方案吗
